# docker run -it -d --name test2 -p 8086:80  ubuntu/apache2:2.4-21.10_edge
# version: "3.9"

services:
  site-1:
    image: ubuntu/apache2:2.4-21.10_edge
    container_name: site1
    volumes:
      - ./site1:/var/www/html
    ports:
      - 80:80
      
  site-2:
    image: ubuntu/apache2:2.4-21.10_edge
    container_name: site2_container
    volumes:
      - ./site2:/var/www/html
    ports:
      - 8081:80
